# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 07:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_question_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 27, 7, 23, 4, 275455, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='metric',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
    ]
