# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 07:38
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20180427_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=apps.core.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
