# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 05:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
