##
# Set up all the dependencies in a virtualenv required  by the django app
# also set up environment variables.
##
---
- name: Create a virtualenv directory
  file: path={{ venv_dir }} state=directory

- name: Install dependencies
  pip: requirements={{ project_dir }}/requirements/production.txt
       virtualenv={{ venv_dir }}
       virtualenv_python=python3.5

- name: Create the .env file for running ad-hoc python commands in the virtualenv
  template: src=env.j2 dest={{ app_dir }}/.env
  become: yes
