##
# Clone and pull the repo
##
---
- name: Set up git configuration
  apt:  name=git-core state=present update_cache=yes
  become: yes

- name: Clone or pull the latest code
  git:  repo={{ code_repository }}
        version={{ git_branch }}
        dest={{ project_dir }}
        accept_hostkey=yes