##
# Clone and pull the repo
##
---
- name: Set up git configuration
  apt:  name=git-core state=present update_cache=yes
  become: yes

- name: Clone or pull the latest code
  git:  repo={{ code_repository_url }}
        version={{ git_branch }}
        dest={{ project_dir }}
        accept_hostkey=yes

- name: Delete all .pyc files
  command: find . -name '*.pyc' -Delete
  args:
    chdir: "{{ project_dir }}"
  changed_when: False