##
# Configure nginx web server
##
- name: Set up nginx config
  apt: name=nginx state=present update_cache=yes
  sudo: yes

- name: ensure default symbolic linked website is deleted
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes

- name: Write nginx conf file
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ app_name }}.conf
  sudo: yes
  notify:
    - restart nginx
