##
# Installs and configures the PosgresSQL database
##
- name: Set up and configure postgres
  apt: name={{ item }}
  sudo: yes
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - python-psycopg2-binary

- name: Create database
  postgresql_db: name={{ app_name }}
  sudo: yes
  sudo_user: postgres

- name: Configure seperate PostgresSQL user
  postgresql_user: db={{ app_name }} name={{ db_user}} password={{ db_password }}
                   priv=ALl role_attr_flags=NOSUPERUSER
  sudo: yes
  sudo_user: postgres
  notify:
    - restart postgres
