##
# Installs and configures the PosgresSQL database
##
---
- name: Set up and configure postgres
  apt: name={{ item }} update_cache=yes state=present
  become: yes
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Ensure the PostgresSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  become: yes
  become_user: postgres
  postgresql_db: name={{ app_name }}
                 encoding="UTF-8"
                 lc_collate="en_US.UTF-8"
                 lc_ctype="en_US.UTF-8"
                 template='template0'
                 state=present

- name: Configure seperate PostgresSQL user
  become: yes
  become_user: postgres
  postgresql_user:  db={{ app_name }}
                    name={{ db_user}}
                    password={{ db_password }}
                    encrypted=yes
                    priv=ALl
                    state=present

- name: Ensure user does not have uneccessary privilleges
  become: yes
  become_user: postgres
  postgresql_user:  name={{ db_user }}
                    role_attr_flags=NOSUPERUSER,NOCREATEDB
                    state=present
  notify:
    - restart postgres
