##
# Installs and configures the PosgresSQL database
##
- name: Set up and configure postgres
  apt: name={{ item }}
  become: yes
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Create database
  postgresql_db: name={{ app_name }}
  become: yes
  become_user: postgres

- name: Configure seperate PostgresSQL user
  postgresql_user: db={{ app_name }} name={{ db_user}} password={{ db_password }}
                   priv=ALl role_attr_flags=NOSUPERUSER
  become: yes
  become_user: postgres
  notify:
    - restart postgres
