##
# Update the apt package cache adn install packages as a root user
##
- name: Install required packages
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  become: yes
  with_items:
    - vim
    - python3-devel
    - python-virtualenv
    - python3-virtualenv
    - python-devel
    - python-setuptools
    - gcc
    - python-pip
    - libjpeg-dev
