##
# Sets up and configures Supervisor which runs Green Unicorn
##
---
- name: Setup Supervisor via the apt package manager
  apt: name=supervisor state=present update_cache=yes
  become: yes

- name: Set supervisor config file
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{ app_name }}.conf.py
  become: yes
  notify: restart supervisor
